server:
  port: 9080

logging:
  level:
    root: INFO

spring:
  flyway:
    enabled: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # XEPDB1 helowin
    url: jdbc:oracle:thin:@localhost:1521/helowin
    username: test
    password: test
  jpa:
    database: oracle
